apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik.k8s.alde.dev
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`alde.dev`)
      kind: Rule
      services:
        - name: blog-service
          port: 80
      middlewares:
        - name: redirect-to-https
          namespace: traefik-system

    - match: Host(`alde.io`)
      kind: Rule
      services:
        - name: blog-service
          port: 80
      middlewares:
        - name: redirect-to-https
          namespace: traefik-system

    - match: Host(`aldehir.com`)
      kind: Rule
      services:
        - name: blog-service
          port: 80
      middlewares:
        - name: redirect-to-https
          namespace: traefik-system

  tls:
    secretName: blog-tls

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-http
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`alde.dev`)
      kind: Rule
      services:
        - name: blog-service
          port: 80
      middlewares:
        - name: redirect-to-https
          namespace: traefik-system

    - match: Host(`alde.io`)
      kind: Rule
      services:
        - name: blog-service
          port: 80
      middlewares:
        - name: redirect-to-https
          namespace: traefik-system

    - match: Host(`aldehir.com`)
      kind: Rule
      services:
        - name: blog-service
          port: 80
      middlewares:
        - name: redirect-to-https
          namespace: traefik-system
